// src/pages/home/index.tsx
import { View as TaroView, Text as TaroText, Image as TaroImage, Textarea as TaroTextarea, Button as TaroButton } from '@tarojs/components'
import { useState, useMemo } from 'react'
import { useStore } from '../../store/useStore'
import classNames from 'classnames'
import Taro from '@tarojs/taro'

const View = TaroView as any
const Text = TaroText as any
const Image = TaroImage as any
const Textarea = TaroTextarea as any
const Button = TaroButton as any

export default function Home() {
  const { user, tasks, toggleTask, addMagnets } = useStore()
  
  // Computed
  const todaysProgress = useMemo(() => {
    const completed = tasks.filter(t => t.completed).length
    const total = tasks.length
    return { completed, total, percentage: total === 0 ? 0 : (completed / total) * 100 }
  }, [tasks])

  // Local State for Modals
  const [showMood, setShowMood] = useState(false)
  const [moodSuccess, setMoodSuccess] = useState(false)
  const [showMoment, setShowMoment] = useState(false)
  const [momentDesc, setMomentDesc] = useState('')
  const [momentAmount, setMomentAmount] = useState(1)

  // --- Handlers ---
  
  const handleMoodConvert = (moodLabel: string) => {
    // 模拟延迟
    Taro.showLoading({ title: '转换心情中...' })
    setTimeout(() => {
      Taro.hideLoading()
      addMagnets(2, `心情转换: 处理了 ${moodLabel}`, 'mood')
      setMoodSuccess(true)
    }, 500)
  }

  const submitMoment = () => {
    if (!momentDesc) return
    addMagnets(momentAmount, `磁贴时刻: ${momentDesc}`, 'magnet-moment')
    setShowMoment(false)
    setMomentDesc('')
    setMomentAmount(1)
    Taro.showToast({ title: '记录成功', icon: 'success' })
  }

  return (
    <View className="min-h-screen bg-[#eff6ff] p-4 pb-24 font-sans">
      {/* Header */}
      <View className="flex items-center justify-between px-2 mb-6">
        <View>
          <Text className="text-xl font-bold text-slate-800 block">你好, {user.name}! 👋</Text>
          <Text className="text-slate-500 text-xs mt-1 block">今天也要加油收集磁贴哦！</Text>
        </View>
        <View className="w-12 h-12 bg-pink-50 rounded-full flex items-center justify-center border-2 border-white shadow-sm overflow-hidden">
           <Text className="text-2xl">🐻</Text>
        </View>
      </View>

      {/* Stats Card */}
      <View className="bg-gradient-to-br from-pink-400 via-rose-400 to-purple-400 rounded-3xl p-6 text-white shadow-xl shadow-pink-200 relative overflow-hidden mb-6">
        <View className="flex justify-between items-start mb-6 relative z-10">
             <View>
                <Text className="text-pink-100 text-xs font-bold mb-1 uppercase tracking-wide block">我的磁贴总数</Text>
                <View className="flex items-center">
                   <Text className="text-6xl font-black">{user.magnets}</Text>
                   <Text className="text-3xl ml-2 opacity-80">🌟</Text>
                </View>
             </View>
             <View className="w-14 h-14 bg-white/20 rounded-full flex items-center justify-center backdrop-blur-md shadow-inner border border-white/20">
                <Text className="text-3xl">🏆</Text>
             </View>
        </View>

        <View className="bg-black/10 rounded-2xl p-4 backdrop-blur-md border border-white/10 relative z-10">
             <View className="flex justify-between items-center mb-2">
                <Text className="text-xs font-bold text-white/90">每日约定场景</Text>
                <Text className="text-xs font-bold text-pink-100">{todaysProgress.completed} / {todaysProgress.total}</Text>
             </View>
             <View className="h-3 bg-black/20 rounded-full overflow-hidden">
                <View 
                  className="h-full bg-gradient-to-r from-yellow-300 to-amber-400 shadow-[0_0_15px_rgba(253,224,71,0.5)] transition-all duration-500 ease-out" 
                  style={{ width: `${todaysProgress.percentage}%` }}
                ></View>
             </View>
        </View>
      </View>

      {/* Quick Actions */}
      <View className="grid grid-cols-2 gap-4 px-1 mb-6">
        <View onClick={() => setShowMoment(true)} className="bg-white p-4 rounded-2xl shadow-sm border border-pink-100 flex flex-col items-center justify-center active:scale-95 transition-all h-28">
           <View className="w-10 h-10 bg-pink-100 text-pink-500 rounded-full flex items-center justify-center text-xl mb-2">
             <Text>📸</Text>
           </View>
           <Text className="text-xs font-bold text-slate-600">磁贴时刻</Text>
        </View>
        <View onClick={() => { setMoodSuccess(false); setShowMood(true); }} className="bg-white p-4 rounded-2xl shadow-sm border border-purple-100 flex flex-col items-center justify-center active:scale-95 transition-all h-28">
           <View className="w-10 h-10 bg-purple-100 text-purple-600 rounded-full flex items-center justify-center text-xl mb-2">
             <Text>🌈</Text>
           </View>
           <Text className="text-xs font-bold text-slate-600">心情转换</Text>
        </View>
      </View>

      {/* Tasks List */}
      <View className="px-1">
         <View className="grid grid-cols-1 gap-3">
            {tasks.map(task => (
                <View 
                    key={task.id}
                    onClick={() => toggleTask(task.id)}
                    className={classNames(
                        "relative overflow-hidden bg-white p-4 rounded-2xl shadow-sm border border-indigo-50 flex items-center transition-all active:scale-[0.98]",
                        { "opacity-80": task.completed }
                    )}
                >
                    {task.completed && (
                        <View className="absolute inset-0 bg-emerald-50/70 flex items-center justify-end pr-6 z-10 backdrop-blur-[1px]">
                            <View className="bg-white px-3 py-1 rounded-full shadow-sm border border-emerald-100 flex items-center">
                                <Text className="text-emerald-600 font-bold text-sm">✓ 完成</Text>
                            </View>
                        </View>
                    )}
                    <View className="w-12 h-12 bg-indigo-50 rounded-full flex items-center justify-center text-2xl mr-4 shrink-0">
                        <Text>{task.icon}</Text>
                    </View>
                    <View className="flex-1 min-w-0">
                        <Text className="font-bold text-slate-800 text-sm block truncate">{task.title}</Text>
                        <View className="mt-1 inline-block bg-indigo-50 px-2 py-0.5 rounded-lg">
                            <Text className="text-xs text-indigo-500 font-bold">+{task.magnetReward} 磁贴</Text>
                        </View>
                    </View>
                </View>
            ))}
         </View>
      </View>

      {/* Modals using root-portal or absolute positioning with high Z */}
      
      {/* Mood Modal */}
      {showMood && (
        <View className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 p-6">
            <View className="bg-white w-full max-w-sm rounded-3xl p-6 shadow-2xl">
                {!moodSuccess ? (
                    <>
                        <Text className="text-lg font-bold text-center block mb-2">🌈 心情转换器</Text>
                        <Text className="text-center text-slate-400 text-xs block mb-6">把小情绪变成正能量！</Text>
                        <View className="grid grid-cols-3 gap-3 mb-6">
                            {[{icon:'😤',label:'生气'},{icon:'😢',label:'难过'},{icon:'😫',label:'疲惫'}].map(m => (
                                <View key={m.label} onClick={() => handleMoodConvert(m.label)} className="flex flex-col items-center justify-center p-4 rounded-2xl bg-slate-50 active:bg-purple-50">
                                    <Text className="text-4xl mb-2">{m.icon}</Text>
                                    <Text className="text-xs font-bold text-slate-600">{m.label}</Text>
                                </View>
                            ))}
                        </View>
                        <Button onClick={() => setShowMood(false)} className="bg-transparent text-slate-400 text-sm">取消</Button>
                    </>
                ) : (
                    <View className="flex flex-col items-center">
                        <Text className="text-4xl mb-4">🎉</Text>
                        <Text className="text-xl font-bold text-purple-600 mb-1">太棒了！</Text>
                        <Text className="text-slate-600 text-sm mb-4">你成功控制了情绪！</Text>
                        <View className="bg-yellow-100 px-4 py-2 rounded-full mb-6">
                            <Text className="text-yellow-800 font-bold text-sm">+2 磁贴 🌟</Text>
                        </View>
                        <Button onClick={() => setShowMood(false)} className="w-full bg-purple-600 text-white rounded-xl font-bold">收下奖励</Button>
                    </View>
                )}
            </View>
        </View>
      )}

      {/* Moment Modal */}
      {showMoment && (
        <View className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 p-6">
            <View className="bg-white w-full max-w-sm rounded-3xl p-6 shadow-2xl">
                <View className="flex justify-between items-center mb-4">
                    <Text className="text-lg font-bold">📸 磁贴时刻</Text>
                    <View onClick={() => setShowMoment(false)}><Text className="text-slate-400">✕</Text></View>
                </View>
                <Text className="text-xs font-bold text-slate-500 mb-2 block">发生了什么美好的事情？</Text>
                <Textarea 
                    value={momentDesc}
                    onInput={(e) => setMomentDesc(e.detail.value)}
                    className="w-full bg-slate-50 rounded-xl p-3 text-sm h-24 mb-4 border border-slate-100"
                    placeholder="例如：主动帮妈妈扫地..." 
                />
                <Text className="text-xs font-bold text-slate-500 mb-2 block">奖励磁贴数量</Text>
                <View className="flex justify-between gap-2 mb-6">
                    {[1,2,3,4,5].map(n => (
                        <View 
                            key={n} 
                            onClick={() => setMomentAmount(n)}
                            className={classNames(
                                "w-10 h-10 rounded-full flex items-center justify-center border-2 font-bold text-sm transition-all",
                                momentAmount === n ? "bg-pink-500 border-pink-500 text-white scale-110" : "bg-white border-slate-100 text-slate-400"
                            )}
                        >
                            <Text>{n}</Text>
                        </View>
                    ))}
                </View>
                <Button onClick={submitMoment} className="bg-pink-500 text-white rounded-xl font-bold">记录并获得奖励</Button>
            </View>
        </View>
      )}
    </View>
  )
}

// src/components/home/home.component.ts

import { Component, inject, signal } from '@angular/core';
import { StoreService } from '../../services/store.service';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { TasksComponent } from '../tasks/tasks.component';
import { LottieAnimationComponent } from '../ui/lottie-animation.component';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [CommonModule, TasksComponent, FormsModule, LottieAnimationComponent],
  template: `
    <div class="space-y-6">
      <!-- Welcome Banner -->
      <div class="flex items-center justify-between px-2">
        <div>
          <h1 class="text-xl font-bold text-slate-800">你好, {{ store.user().name }}! 👋</h1>
          <p class="text-slate-500 text-xs mt-1">今天也要加油收集磁贴哦！</p>
        </div>
        <!-- Avatar -->
        <div class="w-12 h-12 bg-pink-50 rounded-full flex items-center justify-center border-2 border-white shadow-sm overflow-hidden text-2xl">
           🐻
        </div>
      </div>

      <!-- Merged Card: Total Magnets & Daily Progress (Updated Colors) -->
      <div class="bg-gradient-to-br from-pink-400 via-rose-400 to-purple-400 rounded-3xl p-6 text-white shadow-xl shadow-pink-200 relative overflow-hidden transform transition-all active:scale-[0.99]">
        <!-- Top Section: Magnets -->
        <div class="flex justify-between items-start mb-6 relative z-10">
             <div>
                <p class="text-pink-100 text-xs font-bold mb-1 uppercase tracking-wide">我的磁贴总数</p>
                <div class="text-6xl font-black flex items-center drop-shadow-sm tracking-tighter">
                   {{ store.user().magnets }} <span class="text-3xl ml-2 opacity-80">🌟</span>
                </div>
             </div>
             <!-- Trophy Icon -->
             <div class="w-14 h-14 bg-white/20 rounded-full flex items-center justify-center text-3xl backdrop-blur-md shadow-inner border border-white/20">
                🏆
             </div>
        </div>

        <!-- Bottom Section: Daily Progress -->
        <div class="bg-black/10 rounded-2xl p-4 backdrop-blur-md border border-white/10 relative z-10">
             <div class="flex justify-between items-center mb-2">
                <span class="text-xs font-bold text-white/90">每日约定场景</span>
                <span class="text-xs font-bold text-pink-100">{{ store.todaysProgress().completed }} / {{ store.todaysProgress().total }}</span>
             </div>
             <!-- Custom Progress Bar -->
             <div class="h-3 bg-black/20 rounded-full overflow-hidden">
                <div class="h-full bg-gradient-to-r from-yellow-300 to-amber-400 shadow-[0_0_15px_rgba(253,224,71,0.5)] transition-all duration-500 ease-out" 
                     [style.width.%]="store.todaysProgress().percentage"></div>
             </div>
        </div>

        <!-- Decorative bg circles -->
        <div class="absolute -right-8 -top-8 w-56 h-56 bg-white/10 rounded-full blur-3xl pointer-events-none mix-blend-overlay"></div>
        <div class="absolute -left-10 -bottom-10 w-40 h-40 bg-purple-500/20 rounded-full blur-2xl pointer-events-none"></div>
      </div>

      <!-- Quick Actions Grid (Responsive) -->
      <div class="grid grid-cols-2 sm:grid-cols-4 gap-4 px-1">
        
        <!-- 1. Magnet Moment -->
        <button (click)="openMagnetMoment()" class="bg-white hover:bg-pink-50/50 p-4 rounded-2xl shadow-sm border border-pink-100 flex flex-col items-center justify-center space-y-2 active:scale-95 transition-all group h-28 sm:col-span-1">
           <div class="w-10 h-10 bg-pink-100 text-pink-500 rounded-full flex items-center justify-center text-xl group-hover:scale-110 transition-transform shadow-inner">
             📸
           </div>
           <span class="text-xs font-bold text-slate-600">磁贴时刻</span>
        </button>

        <!-- 2. Mood Converter -->
        <button (click)="openMoodModal()" class="bg-white hover:bg-purple-50/50 p-4 rounded-2xl shadow-sm border border-purple-100 flex flex-col items-center justify-center space-y-2 active:scale-95 transition-all group h-28 sm:col-span-1">
           <div class="w-10 h-10 bg-purple-100 text-purple-600 rounded-full flex items-center justify-center text-xl group-hover:scale-110 transition-transform shadow-inner">
             🌈
           </div>
           <span class="text-xs font-bold text-slate-600">心情转换</span>
        </button>

      </div>

      <!-- Integrated Tasks Section -->
      <div class="px-1">
        <app-tasks />
      </div>

      <!-- ============ MODALS ============ -->

      <!-- 1. Magnet Moment Modal -->
      @if (showMagnetMomentModal()) {
        <div class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm animate-fade-in" (click)="closeMagnetMoment()">
           <div class="bg-white rounded-3xl w-full max-w-sm p-6 shadow-2xl animate-pop" (click)="$event.stopPropagation()">
              <div class="flex justify-between items-center mb-4">
                  <h3 class="text-lg font-bold text-slate-800 flex items-center">
                    <span class="mr-2">📸</span> 磁贴时刻
                  </h3>
                  <button (click)="closeMagnetMoment()" class="text-slate-400 hover:text-slate-600">✕</button>
              </div>

              <div class="mb-4">
                <label class="block text-xs font-bold text-slate-500 mb-2">发生了什么美好的事情？</label>
                <textarea 
                  [ngModel]="magnetMomentDescription()"
                  (ngModelChange)="magnetMomentDescription.set($event)"
                  class="w-full bg-slate-50 rounded-xl p-3 text-sm text-slate-900 focus:outline-none focus:ring-2 focus:ring-pink-200 resize-none h-24 placeholder-slate-400 border border-slate-100"
                  placeholder="例如：主动帮妈妈扫地..."
                ></textarea>
              </div>

              <div class="mb-6">
                <label class="block text-xs font-bold text-slate-500 mb-2">奖励磁贴数量</label>
                <div class="flex justify-between gap-2">
                  @for (num of [1,2,3,4,5]; track num) {
                    <button 
                      (click)="setMomentAmount(num)"
                      class="w-10 h-10 rounded-full font-bold transition-all text-sm flex items-center justify-center border-2"
                      [class.bg-pink-500]="magnetMomentAmount() === num"
                      [class.border-pink-500]="magnetMomentAmount() === num"
                      [class.text-white]="magnetMomentAmount() === num"
                      [class.bg-white]="magnetMomentAmount() !== num"
                      [class.border-slate-100]="magnetMomentAmount() !== num"
                      [class.text-slate-400]="magnetMomentAmount() !== num"
                      [class.scale-110]="magnetMomentAmount() === num"
                    >
                      {{ num }}
                    </button>
                  }
                </div>
              </div>
              
              <button 
                (click)="submitMagnetMoment()" 
                [disabled]="!magnetMomentDescription()"
                class="w-full py-3 rounded-xl bg-pink-500 text-white font-bold text-sm shadow-lg shadow-pink-200 active:scale-95 transition-transform disabled:opacity-50 disabled:cursor-not-allowed"
              >
                记录并获得奖励
              </button>
           </div>
        </div>
      }

      <!-- 2. Mood Converter Modal -->
      @if (showMoodModal()) {
        <div class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm animate-fade-in" (click)="closeMoodModal()">
           <div class="bg-white rounded-3xl w-full max-w-sm p-6 shadow-2xl animate-pop text-center" (click)="$event.stopPropagation()">
              
              @if (!moodSuccess()) {
                <h3 class="text-lg font-bold text-slate-800 mb-2 flex items-center justify-center">
                  <span class="mr-2">🌈</span> 心情转换器
                </h3>
                <p class="text-slate-400 text-xs mb-6">选择当前的小情绪，把它变成正能量！</p>

                <div class="grid grid-cols-3 gap-3 mb-6">
                  @for (mood of moods; track mood.label) {
                    <button 
                      (click)="convertMood(mood)"
                      class="flex flex-col items-center justify-center p-4 rounded-2xl bg-slate-50 border-2 border-transparent hover:border-purple-200 hover:bg-purple-50 transition-all active:scale-95"
                    >
                      <span class="text-4xl mb-2 filter drop-shadow-sm">{{ mood.icon }}</span>
                      <span class="text-xs font-bold text-slate-600">{{ mood.label }}</span>
                    </button>
                  }
                </div>
                
                <button (click)="closeMoodModal()" class="text-slate-400 text-sm underline">取消</button>
              } @else {
                <!-- Success State -->
                <div class="flex flex-col items-center py-2">
                  <div class="w-32 h-32 mb-2">
                    <app-lottie 
                      path="https://lottie.host/5ccfe317-5e60-4414-b49d-649033327663/zN1l2E4IqI.json"
                      [loop]="false"
                    />
                  </div>
                  <h4 class="text-xl font-bold text-purple-600 mb-1">太棒了！</h4>
                  <p class="text-slate-600 text-sm mb-4">你成功控制了情绪！</p>
                  <div class="inline-block bg-yellow-100 text-yellow-800 px-4 py-2 rounded-full font-bold shadow-sm mb-6">
                    +2 磁贴 🌟
                  </div>
                  <button (click)="closeMoodModal()" class="w-full py-3 bg-purple-600 text-white rounded-xl font-bold shadow-lg shadow-purple-200 hover:bg-purple-700 transition-colors">
                    收下奖励
                  </button>
                </div>
              }
           </div>
        </div>
      }
    </div>
  `,
  styles: [`
    .animate-fade-in { animation: fadeIn 0.2s ease-out; }
    @keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }
  `]
})
export class HomeComponent {
  store = inject(StoreService);
  
  // Magnet Moment State
  showMagnetMomentModal = signal(false);
  magnetMomentDescription = signal('');
  magnetMomentAmount = signal(1);

  // Mood Converter State
  showMoodModal = signal(false);
  moodSuccess = signal(false);
  moods = [
    { icon: '😤', label: '生气' },
    { icon: '😢', label: '难过' },
    { icon: '😫', label: '疲惫' },
  ];

  // --- Actions ---

  // Navigation
  goToMoments() {
    this.store.activeTab.set('moments');
  }

  // Magnet Moment Logic
  openMagnetMoment() {
    this.magnetMomentDescription.set('');
    this.magnetMomentAmount.set(1);
    this.showMagnetMomentModal.set(true);
  }

  closeMagnetMoment() {
    this.showMagnetMomentModal.set(false);
  }

  setMomentAmount(amount: number) {
    this.magnetMomentAmount.set(amount);
  }

  submitMagnetMoment() {
    if (!this.magnetMomentDescription()) return;

    this.store.addMagnets(
      this.magnetMomentAmount(), 
      `磁贴时刻: ${this.magnetMomentDescription()}`, 
      'magnet-moment'
    );
    this.closeMagnetMoment();
  }

  // Mood Logic
  openMoodModal() {
    this.moodSuccess.set(false);
    this.showMoodModal.set(true);
  }

  closeMoodModal() {
    this.showMoodModal.set(false);
  }

  convertMood(mood: any) {
    // Simulate processing delay for effect
    setTimeout(() => {
        this.store.addMagnets(2, `心情转换: 处理了 ${mood.label} 情绪`, 'mood');
        this.moodSuccess.set(true);
    }, 300);
  }
}
